#更改接口
#server.port=8081
#添加路径
#server.servlet.context-path=/api

#server:
#  port: 8081
#  servlet:
#    context-path: /api
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_bookstore?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverLocation: mysql-connector-java-8.0.15.jar
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active:
      develop

#热部署
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true

---
multipart:
  max-request-size: 20Mb

---
#默认加上路径
server:
  servlet:
    context-path: /api

---
mybatis:
  typeAliasesPackage: com.example.bookstore.modell
  #mapperLocations: classpath:com.example.bookstore.mapper/*.xml
  mapperLocations: classpath:mapper/*.xml
---
